list(APPEND HAZEL_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Buffer.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Buffer.h"
    "${CMAKE_CURRENT_LIST_DIR}/GraphicsContext.h"
    "${CMAKE_CURRENT_LIST_DIR}/Renderer.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Renderer.h"
    "${CMAKE_CURRENT_LIST_DIR}/Shader.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/Shader.h"
    "${CMAKE_CURRENT_LIST_DIR}/VertexArray.h"
    "${CMAKE_CURRENT_LIST_DIR}/VertexArray.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/RendererAPI.h"
    "${CMAKE_CURRENT_LIST_DIR}/RendererAPI.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/RenderCommand.h"
    "${CMAKE_CURRENT_LIST_DIR}/RenderCommand.cpp"
)